simulator_type: libero
task_suite_name: libero_spatial

auto_reset: True
ignore_terminations: True
max_episode_steps: 512

use_rel_reward: True
reward_coef: 5.0
only_eval: True

seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True
num_images_in_input: 1

num_envs: ${env.eval.num_envs}  # Override in main config via env.eval.num_envs
eval_per_task: ${env.eval.eval_per_task}  # Override in main config (documentation: expected evaluations per task)
fixed_task_ids: ${env.fixed_task_ids}  # Override in main config eval.fixed_task_ids

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256